### ISSUE TITLE
Power consumption is too high

### ISSUE THREAD

**Issue by c-MM** [OpenHR20/OpenHR20#10]
The CPU doesn;t go to powersave mode any more, because of this comit:

```
diff --git a/rfmsrc/common/rs232_485_hw.c b/rfmsrc/common/rs232_485_hw.c
index 5497192..3d1f4fa 100644
--- a/rfmsrc/common/rs232_485_hw.c
+++ b/rfmsrc/common/rs232_485_hw.c
@@ -161,7 +161,7 @@ void RS_Init(void)
                          UCSR0B = _BV(RXCIE0) | _BV(RXEN0);
                        #endif
         #else 
-            UCSR0B = _BV(RXCIE0) | _BV(RXEN0);
+            //UCSR0B = _BV(RXCIE0) | _BV(RXEN0);
             UCSR0C = (_BV(UCSZ00) | _BV(UCSZ01));     // Asynchron 8N1
         #endif
        #if !defined(_AVR_IOM16_H_) && !defined(_AVR_IOM32_H_) && !defined(_AVR_IOM328P_H_)
```

If I apply this patch, power consumption is down to around 40uA as opposed to 600uA with the RS232 enabled.

**Comment by KickerTom** [comment]
Wouldn't defining COM_RS232 to 0 have the same effect of disabling RS232? Or are you suggesting that you were able to run with serial enabled and lower power consumption in the past?
Your patch got mangled by github, try using four-space indentation or even the three apostrophe code markdown to display it properly, at this moment I am not sure what change or commit you are talking about.

**Comment by c-MM** [comment]
It is  commit b78a911321b160bcca2b964e08c929b88f54b0a7 1 parent 4f83d99
@bruce33 bruce33 authored on 19 Nov 2012

which introduced this change enabling RS232 on the OpenHR20

**Comment by c-MM** [comment]
I consider this a bug, since a battery life time of around 2-3 months seems a bit short.

For me the code doesn't compile with RS232 defined to 0.

**Comment by KickerTom** [comment]
If the code does not compile with RS232 undefined, it's definitely a problem which should be fixed. All define/undefine paths (which makes sense) should compile and work.
Regarding the change, if the behaviour is worse than what was before, I agree it's a bug (a regression) which should be fixed. But I need a bit more time to study the change and fully evaluate what is going on there and possible side effects, and I am very short on free time at this moment, sorry. But if noone will step up and do this first, I will get back to this issue sooner or later.
Thanks for finding and reporting this problem, every improvement in battery life is always very welcome.

**Comment by c-MM** [comment]
This should be resolved now, with fixing compilation without RS232
