### ISSUE TITLE
Problem with COM_RS232 enabled

### ISSUE THREAD

**Issue by funth1ngs** [OpenHR20/OpenHR20#25]
Hi,

I had some problems with the serial interface (T, G, S... commands) and found a bug in COM_getchar(). The variable COM_requests is decreased for every single time an element is taken from the buffer, but it should only be decreased when c == '\n', like so:

```
    rx_buff_out%=RX_BUFF_SIZE;
    if (c == '\n') {
        COM_requests--;
    }
} else {
```

Cheers!

**Comment by KickerTom** [comment]
I believe this is fixed by merging the changes from @dlemper
