### ISSUE TITLE
[Q] How to enable RS232 only?

### ISSUE THREAD

**Issue by bademux** [OpenHR20/OpenHR20#30]
Hello,
I want to use the thermostat in wired setup.
Can I kindly ask someone to help me configure OpenHR20?

thanks.

**Comment by dlemper** [comment]
Hi bademux,
I'm, too, only using UART/RS232.

I just uncommented the following line:
[config.h:81](https://github.com/OpenHR20/OpenHR20/blob/88e98f4cb085b5625cdc5b6fbc3185ada5f47ee8/rfmsrc/OpenHR20/config.h#L81)

Then compile the sources again und you got serial working!

best regards,
Daniel

**Comment by bademux** [comment]
How I should setup my terminal to communicate with the device?
Is it correct setup?
BAUD: 9600
Data: 8
Parity: N
Stop: 1

**Comment by dlemper** [comment]
yes, thats right!
if you can't get a connection, try to reverse TX and RX

**Comment by dlemper** [comment]
if this solved your problem, please close this issue, thanks!

**Comment by bademux** [comment]
Thanks for the help!
