### ISSUE TITLE
Display is not updating when changing modes

### ISSUE THREAD

**Issue by MartinEderer** [OpenHR20/OpenHR20#32]
If I change via RS232 with M00 and M01 the display is updated from:
-> Manual Mode to Auto after approx. 1 minute
-> Auto Mode to Manual mode sometime after several minutes but sometimes not at all

I add a display update to com.c. I am not sure if thats the best solution (I don't speak C!)
```c
        case 'M':
            if (COM_hex_parse(1*2)!='\0') { break; }
            CTL_change_mode(com_hex[0]);
            COM_print_debug(1);
            display_task = DISP_TASK_CLEAR | DISP_TASK_UPDATE;
            break;
```

**Comment by KickerTom** [comment]
I believe this is now fixed merging the changes from @dlemper.
